=== fontezbrooks/dindinTheGreatRefactor/docs/schema-dindin-swipes-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "__v",
    "createdAt",
    "direction",
    "recipeId",
    "timestamp",
    "updatedAt",
    "userId"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "__v": {
      "type": "integer"
    },
    "createdAt": {
      "$ref": "#/$defs/Date"
    },
    "direction": {
      "type": "string"
    },
    "recipeId": {
      "$ref": "#/$defs/ObjectId"
    },
    "timestamp": {
      "$ref": "#/$defs/Date"
    },
    "updatedAt": {
      "$ref": "#/$defs/Date"
    },
    "userId": {
      "$ref": "#/$defs/ObjectId"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== fontezbrooks/dindinTheGreatRefactor/docs/dindin.swipes.json
[{
  "_id": {
    "$oid": "68a0fc613559578a01176955"
  },
  "userId": {
    "$oid": "000000000000000000000777"
  },
  "recipeId": {
    "$oid": "68a0c60a1d3ed343f5826fa8"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:47:13.337Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:47:13.342Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:47:13.342Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fdcdd13bb7b1cc3c98f7"
  },
  "userId": {
    "$oid": "000000000000000000000724"
  },
  "recipeId": {
    "$oid": "68a0c9d4c1005646cfda908d"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:53:17.641Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:53:17.645Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:53:17.645Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fdd0d13bb7b1cc3c98f9"
  },
  "userId": {
    "$oid": "000000000000000000000724"
  },
  "recipeId": {
    "$oid": "689ca7733c457e835acefadf"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:53:20.549Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:53:20.550Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:53:20.550Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fe9400a141c2060f97bd"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c6ea1d3ed343f5826fb2"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:36.280Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:36.284Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:36.284Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fe9600a141c2060f97c1"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0cb454ffed6f8532020a8"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:38.069Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:38.071Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:38.071Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fe9b00a141c2060f97c4"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c7131d3ed343f5826fb4"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:43.580Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:43.581Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:43.581Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fe9d00a141c2060f97c8"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0cb364ffed6f8532020a7"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:45.144Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:45.144Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:45.144Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fe9f00a141c2060f97cb"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c77c1d3ed343f5826fb9"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:47.592Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:47.592Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:47.592Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fea100a141c2060f97ce"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0cb614ffed6f8532020a9"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:49.397Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:49.397Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:49.397Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0fea400a141c2060f97d1"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0caf94ffed6f8532020a4"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:52.856Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:52.856Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:52.856Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a0feaa00a141c2060f97d5"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68960cee0b425688e3bc3fe1"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T21:56:58.784Z"
  },
  "createdAt": {
    "$date": "2025-08-16T21:56:58.784Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T21:56:58.784Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1011300a141c2060f97d8"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c9d4c1005646cfda908d"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:15.595Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:15.596Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:15.596Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1011500a141c2060f97db"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c9a6c1005646cfda908b"
  },
  "direction": "left",
  "timestamp": {
    "$date": "2025-08-16T22:07:17.198Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:17.199Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:17.199Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1011600a141c2060f97de"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "6896c9aa60d6fa4f11f56a02"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:18.421Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:18.422Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:18.422Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1011800a141c2060f97e2"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "6896c9e060d6fa4f11f56a05"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:20.890Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:20.891Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:20.891Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1011a00a141c2060f97e6"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c6241d3ed343f5826fa9"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:22.214Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:22.214Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:22.214Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1012700a141c2060f97ea"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0ca13c1005646cfda9090"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:35.336Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:35.337Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:35.337Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1012900a141c2060f97ed"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "689ca73f3c457e835acefade"
  },
  "direction": "left",
  "timestamp": {
    "$date": "2025-08-16T22:07:37.716Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:37.717Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:37.717Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1012b00a141c2060f97f0"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c9b8c1005646cfda908c"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:39.656Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:39.656Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:39.656Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1012d00a141c2060f97f3"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "6896c9ce60d6fa4f11f56a04"
  },
  "direction": "left",
  "timestamp": {
    "$date": "2025-08-16T22:07:41.187Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:41.188Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:41.188Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1012e00a141c2060f97f6"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0cb8a4ffed6f8532020ab"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:42.440Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:42.441Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:42.441Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1013100a141c2060f97f9"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c60a1d3ed343f5826fa8"
  },
  "direction": "left",
  "timestamp": {
    "$date": "2025-08-16T22:07:45.304Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:45.305Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:45.305Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1013400a141c2060f97fc"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68960d200b425688e3bc3fe4"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:48.819Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:48.819Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:48.819Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1013600a141c2060f97ff"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c9e4c1005646cfda908e"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:50.122Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:50.123Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:50.123Z"
  },
  "__v": 0
},
{
  "_id": {
    "$oid": "68a1013700a141c2060f9803"
  },
  "userId": {
    "$oid": "000000000000000000000792"
  },
  "recipeId": {
    "$oid": "68a0c6d31d3ed343f5826fb1"
  },
  "direction": "right",
  "timestamp": {
    "$date": "2025-08-16T22:07:51.656Z"
  },
  "createdAt": {
    "$date": "2025-08-16T22:07:51.656Z"
  },
  "updatedAt": {
    "$date": "2025-08-16T22:07:51.656Z"
  },
  "__v": 0
},
{
  "_id": {
